add_executable(BuiltinCommands.unittests BuiltinCommandsTest.cpp BuiltinDateTest.cpp BuiltinSizeTest.cpp ChmodPathsTest.cpp CmpTest.cpp CpTest.cpp CutTest.cpp DateTest.cpp DuTest.cpp EnvTest.cpp FindTest.cpp BuiltinTextTest.cpp FnmatchTest.cpp GrepTest.cpp HeadTest.cpp ManTest.cpp MvTest.cpp NlTest.cpp PrintfTest.cpp RmTest.cpp SeqTest.cpp SortTest.cpp StatTest.cpp TailTest.cpp TeeTest.cpp TestTest.cpp TouchTest.cpp TrTest.cpp UniqTest.cpp WcTest.cpp WhichSleepTrueFalseTest.cpp)
target_include_directories(BuiltinCommands.unittests PRIVATE ${CMAKE_SOURCE_DIR}/src/components/Factory)
target_link_libraries(BuiltinCommands.unittests PRIVATE gtest_main BuiltinCommands Factory)
target_compile_features(BuiltinCommands.unittests PRIVATE cxx_std_17)